[package]
name = "ml-kem-easy"
version = "0.2.0"
edition = "2024"


[dependencies]
getrandom = "0.4.1"
sha3 = "0.11.0-rc.7"

[dev-dependencies]
hex = "0.4.3"

[features]
default = ["ML_KEM_768"]
ML_KEM_512 = []
ML_KEM_768 = []
ML_KEM_1024 = []
